# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainMasopust.ui'
#
# Created: Mon Jan  9 22:00:12 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1389, 901)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui/icons/Rock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pilesGraphicsView_2 = QtGui.QGraphicsView(self.centralwidget)
        self.pilesGraphicsView_2.setMinimumSize(QtCore.QSize(800, 600))
        self.pilesGraphicsView_2.setMaximumSize(QtCore.QSize(800, 600))
        self.pilesGraphicsView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pilesGraphicsView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pilesGraphicsView_2.setObjectName("pilesGraphicsView_2")
        self.gridLayout_3.addWidget(self.pilesGraphicsView_2, 0, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.layersTab = QtGui.QWidget()
        self.layersTab.setObjectName("layersTab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layersTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.addLayerButton = QtGui.QPushButton(self.layersTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ui/icons/Plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addLayerButton.setIcon(icon1)
        self.addLayerButton.setObjectName("addLayerButton")
        self.gridLayout.addWidget(self.addLayerButton, 1, 0, 1, 1)
        self.removeLayerButton = QtGui.QPushButton(self.layersTab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ui/icons/Minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeLayerButton.setIcon(icon2)
        self.removeLayerButton.setObjectName("removeLayerButton")
        self.gridLayout.addWidget(self.removeLayerButton, 1, 2, 1, 1)
        self.layersView = QtGui.QTableView(self.layersTab)
        self.layersView.setObjectName("layersView")
        self.gridLayout.addWidget(self.layersView, 2, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.layersTab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stiffnessLayout = QtGui.QGridLayout()
        self.stiffnessLayout.setObjectName("stiffnessLayout")
        self.stiffnessDynamicGridLayout = QtGui.QGridLayout()
        self.stiffnessDynamicGridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.stiffnessDynamicGridLayout.setObjectName("stiffnessDynamicGridLayout")
        self.stiffnessLayout.addLayout(self.stiffnessDynamicGridLayout, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.stiffnessLayout)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.webLayout = QtGui.QVBoxLayout()
        self.webLayout.setObjectName("webLayout")
        self.horizontalLayout_2.addLayout(self.webLayout)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalForceLineEdit = QtGui.QLineEdit(self.tab_2)
        self.verticalForceLineEdit.setObjectName("verticalForceLineEdit")
        self.gridLayout_2.addWidget(self.verticalForceLineEdit, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 3, 3, 1)
        self.consoleBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.consoleBrowser.setMinimumSize(QtCore.QSize(800, 200))
        self.consoleBrowser.setMaximumSize(QtCore.QSize(800, 200))
        self.consoleBrowser.setObjectName("consoleBrowser")
        self.gridLayout_3.addWidget(self.consoleBrowser, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAddLayer = QtGui.QAction(MainWindow)
        self.actionAddLayer.setIcon(icon1)
        self.actionAddLayer.setObjectName("actionAddLayer")
        self.actionRemove = QtGui.QAction(MainWindow)
        self.actionRemove.setIcon(icon2)
        self.actionRemove.setObjectName("actionRemove")
        self.actionSettings = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ui/icons/Settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon3)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ui/icons/Cancel 2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionRun = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ui/icons/Calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon5)
        self.actionRun.setObjectName("actionRun")
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionRun, QtCore.SIGNAL("triggered()"), MainWindow.runAction)
        QtCore.QObject.connect(self.layersView, QtCore.SIGNAL("clicked(QModelIndex)"), MainWindow.findRow)
        QtCore.QObject.connect(self.removeLayerButton, QtCore.SIGNAL("clicked()"), MainWindow.removeLayer)
        QtCore.QObject.connect(self.verticalForceLineEdit, QtCore.SIGNAL("editingFinished()"), MainWindow.sendAllStats)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL("currentChanged(int)"), MainWindow.tabChanged)
        QtCore.QObject.connect(self.addLayerButton, QtCore.SIGNAL("clicked()"), MainWindow.addLayer)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "AGeo", None, QtGui.QApplication.UnicodeUTF8))
        self.addLayerButton.setText(QtGui.QApplication.translate("MainWindow", "Přidat vrstvu", None, QtGui.QApplication.UnicodeUTF8))
        self.removeLayerButton.setText(QtGui.QApplication.translate("MainWindow", "Odebrat vrstvu", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.layersTab), QtGui.QApplication.translate("MainWindow", "Zadání piloty a zeminy", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Dodatečné parametry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Vertikální síla v hlavě piloty V=", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalForceLineEdit.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Specifikace zatížení", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Provozní", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Extrémní", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Zatížení", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddLayer.setText(QtGui.QApplication.translate("MainWindow", "Add Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddLayer.setToolTip(QtGui.QApplication.translate("MainWindow", "Add new layer of soil", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove layer of soil", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Setting up UI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setToolTip(QtGui.QApplication.translate("MainWindow", "Exit program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "Spustit výpočet", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
